import type {Metadata} from "next";
import "./globals.css";
import Providers from "@/app/Provider";
import AppReadyNotifier from './AppReadyNotifier'
import {ThemeProvider} from "next-themes";
import React from "react";
import {SidebarLayout} from "@/app/provider/SidebarProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>
        <Providers>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                <AppReadyNotifier/>
                <SidebarLayout>
                    {children}
                </SidebarLayout>
            </ThemeProvider>
        </Providers>
        </body>
        </html>
    );
}
