name: Release Tauri on main

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} • Tauri
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu

    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JS deps
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust_target }}

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri -> target

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf


      - name: Build & Publish Release
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: main                      # Вариант A: «rolling» релиз, всегда один и тот же тег
          releaseName: "Rolling release (main)"
          releaseBody: "Automated build from branch main: ${{ github.sha }}"
          releaseDraft: false
          prerelease: false
