name: Release Tauri on main

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} • Tauri
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu

    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install JS deps
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust_target }}

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri -> target

      # Linux: GTK + WebKit2GTK + AppIndicator + RSVG + линковка
      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libsoup-3.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config \
            patchelf
          # WebKit2GTK: пробуем 4.1, если нет — ставим 4.0
          sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Build & Publish Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Автотег и имя релиза по версии из package.json/tauri.conf.json
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseBody: "Automated build from branch main: ${{ github.sha }}"
          releaseDraft: false
          prerelease: false
